// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7pWZU6Ol8i4BcA1-j3L9gkYcMwCADVZ0',
    appId: '1:427334465779:web:9f2a357b34d99110149f86',
    messagingSenderId: '427334465779',
    projectId: 'fintracker-96098',
    authDomain: 'fintracker-96098.firebaseapp.com',
    storageBucket: 'fintracker-96098.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfadAotmmqcKQVM5NchhmqHL0nZPseE50',
    appId: '1:427334465779:android:7e6e09e6109eb70c149f86',
    messagingSenderId: '427334465779',
    projectId: 'fintracker-96098',
    storageBucket: 'fintracker-96098.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8YCQvP1rhpiQZfXjXht5YirFAZOyICjI',
    appId: '1:427334465779:ios:0ea791e1df6ddaa5149f86',
    messagingSenderId: '427334465779',
    projectId: 'fintracker-96098',
    storageBucket: 'fintracker-96098.firebasestorage.app',
    iosBundleId: 'com.example.flutterFintracker',
  );
}
